server:
  port: 8081
spring:
  application:
    name: index
    discovery:
      enabled: true
      serviceId: config
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/